### ISSUE TITLE
Enemy 1 - Snail

### ISSUE THREAD

**Issue by WestonVincze** [Roasted-Goblin-Studio/7DRL-Jam#12]
![image](https://user-images.githubusercontent.com/16705858/156894995-5d232fae-b550-48bf-99f5-1120558c3057.png)

Simple enemy, meant for tutorial
A slow moving enemy with a melee attack

# Acceptance criteria
- Slow Movement
- Low damage
- Melee only
- Medium health

# Stretch 
Slime Trail

**Comment by PhillypHenning** [comment]
https://github.com/Roasted-Goblin-Studio/7DRL-Jam/tree/AI/Snail

**Comment by PhillypHenning** [comment]
- Slow Movement
- Medium health (3)
