### ISSUE TITLE
Enemy 2 - Flying Book

### ISSUE THREAD

**Issue by WestonVincze** [Roasted-Goblin-Studio/7DRL-Jam#15]
![image](https://user-images.githubusercontent.com/16705858/156895102-54db7f20-a8fc-4ad3-b5af-3fa41df8c4a1.png)

A fast-paced enemy meant to be a bit more challenging than Enemy 1

# Acceptance Criteria
- Bite melee attack
- Possible Ranged attack
- Fast speed
- Low health

**Comment by PhillypHenning** [comment]
Started with https://github.com/Roasted-Goblin-Studio/7DRL-Jam/tree/AI/Book
