### ISSUE TITLE
Enemy 3 - Eye

### ISSUE THREAD

**Issue by WestonVincze** [Roasted-Goblin-Studio/7DRL-Jam#17]
![image](https://user-images.githubusercontent.com/16705858/156895210-e10a06e3-9639-4146-a7ac-75d574187c5f.png)

# Acceptance Criteria
- ~Melee attack~
- Ranged attack - Shotgun
- Spawn mini kamikaze eyeballs
- Medium speed
- Medium damage

# Stretch Goals
- Spawning small brood enemies

**Comment by PhillypHenning** [comment]
# Finshed https://github.com/Roasted-Goblin-Studio/7DRL-Jam/pull/68
- Ranged attack - Shotgun
- Medium speed

**Comment by PhillypHenning** [comment]
Closed with https://github.com/Roasted-Goblin-Studio/7DRL-Jam/pull/68
